export const ActionTypes = {
	SET_PRODUCTS: "SET_PRODUCTS",
	SELECTED_PRODUCT: "SELECTED_PRODUCT",
	REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
	ADD_CART: "ADD_CART",
	DEL_CART: "DEL_CART",
	ADJUST_QTY: "ADJUST_QTY",
};
